// The single-message reply train (operator 2026-06-30): ONE message, opened eagerly
// as the "⏳ Thinking…" reply placeholder (instant ack + streaming target; id resolves
// during spin-up), edited in place into the answer. No separate knee-jerk (it piled up
// / cross-deleted in busy chats). body_emoji stamping is the port's job (locked in
// beeper-port.test); the FAKE bridge records raw text, so these assert the SENDER's
// markers (⏳ / ❌) + the reply-to placeholder. The reply carries NO inline end-marker:
// the historical signature / ∎ was removed (operator 2026-07-12) — the sole agent close
// is the agent_signature_close layer, applied downstream in the port (default empty).
import { describe, it, expect } from 'vitest';
import { createSender, RETAINED_SEAM } from '../src/spine/sender.mjs';
import { LIVE_FRAME_MARK } from '../src/dispatch-line.mjs';

function fakeBridge() {
  const streams = [], sent = [];
  return {
    streams, sent,
    send(chat, text, opts) { sent.push({ chat, text, opts }); },
    startStream(chat, init, opts) {
      const h = {
        chat, init, opts, frames: [], finals: [], deleted: false, delivered: false,
        update(t) { h.frames.push(t); },
        async finish(t) { h.finals.push(t); h.delivered = true; },
        async delete() { h.deleted = true; },
      };
      streams.push(h); return h;
    },
  };
}

describe('sender — single-message reply train', () => {
  it('opens ONE "⏳ Thinking…" reply placeholder, streams with ⏳, ends with the BARE reply — NO end-marker (no separate knee-jerk)', async () => {
    const bridge = fakeBridge();
    const out = createSender({ bridge, bodyEmojiOf: () => '🐶' }).open('!c', { being: 'e', replyTo: 'm1' });
    expect(bridge.streams).toHaveLength(1);
    expect(bridge.streams[0].init).toBe('⏳ Thinking…');             // the eager placeholder = instant ack + target
    expect(bridge.streams[0].opts).toMatchObject({ replyTo: 'm1', bodyEmoji: '🐶', persona: 'e' });
    out.update('Hola');
    expect(bridge.streams[0].frames).toEqual(['Hola ⏳']);
    await out.finish({ text: 'Hola mundo' });
    expect(bridge.streams[0].finals).toEqual(['Hola mundo']);       // bare reply — no trailing ∎ / end-marker (behavior CHANGE 2026-07-12)
    expect(bridge.sent).toHaveLength(0);                             // delivered in place — no fallback
  });

  it("not surfaced: the MODEL's own '...' passes through, never deleted", async () => {
    // operator 2026-08-24: "'...' must only be generated by the model". If the
    // model chose silence, that IS its word and it is surfaced as-is.
    const bridge = fakeBridge();
    const out = createSender({ bridge, bodyEmojiOf: () => '🐶' }).open('!c', { being: 'e' });
    await out.finish({ text: '...' }, { surface: false });
    expect(bridge.streams[0].deleted).toBe(false);
    expect(bridge.streams[0].finals).toEqual(['...']);
    expect(bridge.sent).toHaveLength(0);
  });

  it("not surfaced with NOTHING from the model: the bridge says so in its own voice", async () => {
    // The bridge must never fabricate the model's '...' — a silence it invented
    // is indistinguishable from one the being chose.
    const bridge = fakeBridge();
    const out = createSender({ bridge, bodyEmojiOf: () => '🐶' }).open('!c', { being: 'e' });
    await out.finish({ text: '' }, { surface: false });
    expect(bridge.streams[0].deleted).toBe(false);
    expect(bridge.streams[0].finals).toEqual(['<received silence (error?)>']);
  });

  it('surfaced but EMPTY (turn failed/empty): resolves VISIBLY with the no-reply marker, does NOT delete (DEFECT 1)', async () => {
    const bridge = fakeBridge();
    const out = createSender({ bridge }).open('!c', { being: 'e', replyTo: 'm1' });
    await out.finish({ text: '' }, { surface: true });   // meant to surface, nothing came back
    expect(bridge.streams[0].deleted).toBe(false);       // NOT silently deleted / left stuck
    expect(bridge.streams[0].finals).toEqual(['⚠️ no reply (turn failed/empty)']);   // bare marker — no signature (2026-07-12)
    expect(bridge.sent).toHaveLength(0);                 // delivered in place, no fallback
  });

  it('falls back to a fresh send when the in-place edit did not deliver (§7)', async () => {
    const bridge = fakeBridge();
    bridge.startStream = (chat, init, opts) => { const h = { update() {}, async finish() {}, async delete() {}, delivered: false }; bridge.streams.push(h); return h; };
    const out = createSender({ bridge, bodyEmojiOf: () => '🐶' }).open('!c', { being: 'e', replyTo: 'm1' });
    await out.finish({ text: 'reply' });
    // The tag now also carries the per-agent signature-wrap slots (empty by default → the port adds nothing).
    // The core is the BARE reply — no inline ∎ / end-marker (2026-07-12); any agent close is a port-side layer.
    expect(bridge.sent).toEqual([{ chat: '!c', text: 'reply', opts: { bodyEmoji: '🐶', label: null, replyTo: 'm1', agentSigOpen: '', agentSigClose: '' } }]);
  });

  it('send failure ends the message with ❌', async () => {
    const bridge = fakeBridge();
    const out = createSender({ bridge }).open('!c', { being: 'e' });
    out.update('partial');
    await out.fail(new Error('boom'));
    expect(bridge.streams[0].finals[0]).toMatch(/partial … ❌ Sending failed\./);
  });

  // NO inline end-marker by default (operator 2026-07-12): the historical signature / ∎ train
  // terminator was REMOVED — the sender emits the BARE reply, and the sole agent close is now the
  // agent_signature_close LAYER (applied by the port). With no agent_signature_close configured a
  // reply carries no end-marker at all — neither the reply nor the no-reply marker gets one.
  it('with NO agent_signature_close configured, the reply + the no-reply marker carry NO end-marker', async () => {
    const bridge = fakeBridge();
    const sender = createSender({ bridge, bodyEmojiOf: () => '🐦' });   // no agentSignatureCloseOf → defaults to ''
    const out = sender.open('!c', { being: 'wren', replyTo: 'm1' });
    await out.finish({ text: 'listo' });
    expect(bridge.streams[0].finals).toEqual(['listo']);          // bare reply — no trailing ∎ / signature

    const out2 = sender.open('!c', { being: 'wren' });
    await out2.finish({ text: '' }, { surface: true });           // empty → bare no-reply marker, no signature
    expect(bridge.streams[1].finals).toEqual(['⚠️ no reply (turn failed/empty)']);
  });

  // MULTILINE agent_signature_close (constraint #4, operator 2026-07-12): the agent close may be
  // multiline; the sender threads it VERBATIM into the tag (the PORT wraps it as a block below the
  // core), so the newline survives — verified here so a later refactor can't flatten it.
  it('a MULTILINE agent_signature_close threads verbatim into the tag (newline preserved, not flattened)', async () => {
    const bridge = fakeBridge();
    const agentSignatureCloseOf = () => 'line1\nline2';
    const out = createSender({ bridge, bodyEmojiOf: () => '🐶', agentSignatureCloseOf }).open('!c', { being: 'e', replyTo: 'm1' });
    expect(bridge.streams[0].opts).toMatchObject({ agentSigClose: 'line1\nline2' });   // block survives — newline intact
  });

  // PER-AGENT signature-wrap slots (operator 2026-07-12): the sender resolves agent_signature_open/close
  // per-being (agent → node → '', via the injected agentSignature*Of resolvers) and threads them into the
  // tag; the PORT does the concentric wrap. Here the fake bridge just records the tag, so this locks the
  // resolution + hand-off.
  it('threads the being\'s resolved agent_signature open/close into the stream + fallback tag', async () => {
    const bridge = fakeBridge();
    bridge.startStream = (chat, init, opts) => { const h = { update() {}, async finish() {}, async delete() {}, delivered: false, opts }; bridge.streams.push(h); return h; };
    const agentSignatureOpenOf = (being) => (being === 'wren' ? '⟨wren⟩' : '');
    const agentSignatureCloseOf = (being) => (being === 'wren' ? '⟨/wren⟩' : '');
    const out = createSender({ bridge, bodyEmojiOf: () => '🐦', agentSignatureOpenOf, agentSignatureCloseOf })
      .open('!c', { being: 'wren', replyTo: 'm1' });
    expect(bridge.streams[0].opts).toMatchObject({ agentSigOpen: '⟨wren⟩', agentSigClose: '⟨/wren⟩' });
    await out.finish({ text: 'listo' });   // stream did not deliver → §7 fallback send carries the same tag
    expect(bridge.sent[0].opts).toMatchObject({ agentSigOpen: '⟨wren⟩', agentSigClose: '⟨/wren⟩' });
  });
});

// THE MESSAGE IS APPEND-ONLY (operator 2026-08-28): "the message is replaced for a 'final'
// message, and the in-transit thinking is deleted … sometimes it is writing something and then
// boom, it changes … the messages should also be stable". Every edit used to SUPERSEDE the last,
// so a settled reply that was not an EXTENSION of the streamed text erased what a human had
// already read. The invariant these lock: each value the message takes has its predecessor as a
// literal PREFIX. `stable` below is the whole train — every streamed frame (marker stripped) plus
// the settle — which is exactly the sequence a human watches.
describe('sender — the message never shrinks (append-only living mirror)', () => {
  const stable = (h) => [...h.frames.map((f) => f.replace(new RegExp(` ${LIVE_FRAME_MARK}$`), '')), ...h.finals];
  const monotone = (texts) => {
    for (let i = 1; i < texts.length; i++) expect(texts[i].startsWith(texts[i - 1])).toBe(true);
  };

  it('a settled reply that DIVERGES from the narration keeps the narration and reads as the answer LAST', async () => {
    // warm-cli resolves with `ev.result` — the LAST assistant message, not the accumulated
    // train — so the settle is routinely NOT an extension of what streamed.
    const bridge = fakeBridge();
    const out = createSender({ bridge }).open('!c', { being: 'e', replyTo: 'm1' });
    out.update('Voy a mirar');
    out.update('Voy a mirar el archivo…');
    await out.finish({ text: 'El archivo tiene 42 líneas.' });

    const final = bridge.streams[0].finals[0];
    expect(final).toContain('Voy a mirar el archivo…');            // NOTHING shown is removed
    expect(final.startsWith('Voy a mirar el archivo…')).toBe(true);  // the narration stays where it was
    expect(final.endsWith('El archivo tiene 42 líneas.')).toBe(true);// the settled answer is the LAST block
    expect(final).toBe(`Voy a mirar el archivo…${RETAINED_SEAM}El archivo tiene 42 líneas.`);
    monotone(stable(bridge.streams[0]));
    expect(bridge.streams[0].deleted).toBe(false);
  });

  it('a MID-STREAM divergence seals once — the tail keeps growing under the SAME seam, never duplicated', async () => {
    // codex assigns `currentTurn.text = item.text` wholesale on item/completed and then keeps
    // streaming the next item's deltas onto it, so a turn can diverge mid-flight and continue.
    const bridge = fakeBridge();
    const out = createSender({ bridge }).open('!c', { being: 'e' });
    out.update('primer intento');
    out.update('respuesta');            // wholesale replacement mid-stream
    out.update('respuesta buena');      // …which then extends normally
    await out.finish({ text: 'respuesta buena' });

    const h = bridge.streams[0];
    expect(h.finals).toEqual([`primer intento${RETAINED_SEAM}respuesta buena`]);
    expect(h.finals[0].split('respuesta buena')).toHaveLength(2);   // ONE copy — the seam is not re-stamped
    monotone(stable(h));
  });

  it('a pure-APPEND stream settles with the answer alone — no seam, no retained duplicate', async () => {
    const bridge = fakeBridge();
    const out = createSender({ bridge }).open('!c', { being: 'e' });
    out.update('Hola');
    out.update('Hola mun');
    await out.finish({ text: 'Hola mundo' });
    expect(bridge.streams[0].finals).toEqual(['Hola mundo']);       // the ordinary case is untouched
    monotone(stable(bridge.streams[0]));
  });

  it('the seam carries NO live marker — a peer node must still record the settle as history', () => {
    // isLiveStreamFrame (372c17f) classifies by the marker's PRESENCE anywhere in the frame,
    // so a seam containing ⏳ would make every settled message look transient to an observing
    // node and drop it from that node's transcript.
    expect(RETAINED_SEAM).not.toContain(LIVE_FRAME_MARK);
  });

  it('an empty/withheld settle still keeps what was already read (marker below the seam, nothing erased)', async () => {
    const bridge = fakeBridge();
    const sender = createSender({ bridge });
    const out = sender.open('!c', { being: 'e' });
    out.update('lo estoy mirando');
    await out.finish({ text: '' }, { surface: true });              // meant to surface, nothing came back
    expect(bridge.streams[0].finals).toEqual([`lo estoy mirando${RETAINED_SEAM}⚠️ no reply (turn failed/empty)`]);

    const out2 = sender.open('!c', { being: 'e' });
    out2.update('lo estoy mirando');
    await out2.finish({ text: '' }, { surface: false });            // withheld with nothing from the model
    expect(bridge.streams[1].finals).toEqual([`lo estoy mirando${RETAINED_SEAM}<received silence (error?)>`]);
  });

  it('a send failure ends the message with ❌ WITHOUT eating a divergent narration', async () => {
    const bridge = fakeBridge();
    const out = createSender({ bridge }).open('!c', { being: 'e' });
    out.update('empiezo');
    out.update('otra cosa');                                        // divergence
    await out.fail(new Error('boom'));
    expect(bridge.streams[0].finals).toEqual([`empiezo${RETAINED_SEAM}otra cosa … ❌ Sending failed.`]);
  });
});

// mode:auto — E impersonates the operator (operator 2026-07-05): the reply is PLAIN
// operator text. NO thinking scaffold (no "⏳ Thinking…" placeholder, no streamed edits)
// and NO persona tag (no bodyEmoji/label → the port stamps nothing). It posts ONCE,
// complete, on finish; a withheld/empty reply posts nothing.
describe('sender — mode:auto post-once (no persona head, no thinking train)', () => {
  it('posts ONCE as plain text: no placeholder/stream ever opens, streamed tokens ignored, no bodyEmoji/label', async () => {
    const bridge = fakeBridge();
    const out = createSender({ bridge, bodyEmojiOf: () => '🐶', labelOf: () => 'egpt' }).open('!c', { being: 'e', replyTo: 'm1', auto: true });
    expect(bridge.streams).toHaveLength(0);                    // NO thinking train opened
    out.update('partial');                                     // streamed tokens are dropped in auto
    await out.finish({ text: 'Hey, all good' });
    expect(bridge.streams).toHaveLength(0);                    // still none — post-once only
    expect(bridge.sent).toEqual([{ chat: '!c', text: 'Hey, all good', opts: { replyTo: 'm1' } }]);   // plain: no bodyEmoji/label
  });

  it('a withheld (silence) or empty auto reply posts NOTHING — staying silent is a valid operator move', async () => {
    const bridge = fakeBridge();
    const out = createSender({ bridge, bodyEmojiOf: () => '🐶' }).open('!c', { being: 'e', auto: true });
    await out.finish({ text: '' }, { surface: true });          // empty
    await out.finish({ text: 'x' }, { surface: false });         // withheld ('…' silence)
    expect(bridge.sent).toHaveLength(0);
    expect(bridge.streams).toHaveLength(0);
  });
});

// PER-BEING CONNECTION ROUTING (operator 2026-08-30, multi-connection Beeper): bridgeOf is an
// OPTIONAL (being) => Bridge selector, resolved per open() call (open() already receives
// `being`) — a node wired to more than one Beeper account routes each being's reply through its
// OWN bridge instance. The `bridge` param stays REQUIRED and is the fallback: absent bridgeOf,
// or bridgeOf(being) returning nullish, must behave exactly like every test above this block
// (which pass only `bridge`) — additive, never a change to that existing path.
describe('sender — bridgeOf: per-being connection routing (multi-connection Beeper)', () => {
  it('bridgeOf present: each being streams + falls back through its OWN bridge — no cross-talk', async () => {
    const mainBridge = fakeBridge();
    const rodzBridge = fakeBridge();
    const bridgeOf = (being) => (being === 'rodz' ? rodzBridge : null);   // null for e/egpt → falls back to the default `bridge`
    const sender = createSender({ bridge: mainBridge, bridgeOf, bodyEmojiOf: () => '🐶', labelOf: (b) => b });

    const outMain = sender.open('!c1', { being: 'egpt', replyTo: 'm1' });
    await outMain.finish({ text: 'from egpt' });
    const outRodz = sender.open('!c2', { being: 'rodz', replyTo: 'm2' });
    await outRodz.finish({ text: 'from rodz' });

    expect(mainBridge.streams).toHaveLength(1);
    expect(mainBridge.streams[0].finals).toEqual(['from egpt']);
    expect(rodzBridge.streams).toHaveLength(1);
    expect(rodzBridge.streams[0].finals).toEqual(['from rodz']);
    // no cross-talk: neither bridge saw the other being's frames
    expect(mainBridge.sent).toHaveLength(0);
    expect(rodzBridge.sent).toHaveLength(0);
  });

  it('bridgeOf absent (the default path, every other caller): unchanged — every send rides the single `bridge`', async () => {
    const bridge = fakeBridge();
    const sender = createSender({ bridge, bodyEmojiOf: () => '🐶' });   // no bridgeOf — mirrors memberSender + every caller above this block
    const out = sender.open('!c', { being: 'e', replyTo: 'm1' });
    await out.finish({ text: 'hi' });
    expect(bridge.streams).toHaveLength(1);
    expect(bridge.streams[0].finals).toEqual(['hi']);
  });

  it('bridgeOf returns nullish for a being: falls back to the default `bridge`, never throws', async () => {
    const bridge = fakeBridge();
    const sender = createSender({ bridge, bridgeOf: () => null, bodyEmojiOf: () => '🐶' });
    const out = sender.open('!c', { being: 'e', replyTo: 'm1' });
    await out.finish({ text: 'hi' });
    expect(bridge.streams).toHaveLength(1);
    expect(bridge.streams[0].finals).toEqual(['hi']);
  });
});
