# register-startup.ps1 -- install the egpt daemon supervisor into the Startup folder,
# replacing the (proven unreliable on some Windows editions) egpt-daemon-session1 and
# egpt-daemon-watchdog scheduled tasks. See startup-supervisor.ps1's own header for the
# full "why".
#
# Drops a tiny .vbs launcher DIRECTLY into shell:startup (no shortcut file needed -- Windows
# auto-runs anything placed there, .vbs included, as part of Explorer's own logon sequence).
# The launcher's only job is: run startup-supervisor.ps1 hidden, don't wait for it (it loops
# forever). Idempotent -- re-run to update after moving/editing the repo.
#
#   powershell -ExecutionPolicy Bypass -File .\setup\register-startup.ps1

param(
  [string]$Repo     = (Join-Path $env:USERPROFILE 'bin\egpt'),
  [string]$EgptHome = $(if ($env:EGPT_HOME) { $env:EGPT_HOME } else { Join-Path $env:USERPROFILE '.egpt' })
)

$ErrorActionPreference = 'Stop'

$supervisorScript = Join-Path $Repo 'setup\startup-supervisor.ps1'
if (-not (Test-Path $supervisorScript)) { throw "supervisor script not found: $supervisorScript" }

$startupDir = Join-Path $env:APPDATA 'Microsoft\Windows\Start Menu\Programs\Startup'
if (-not (Test-Path $startupDir)) { throw "Startup folder not found: $startupDir" }
$launcherPath = Join-Path $startupDir 'egpt-daemon-supervisor.vbs'

$q = [char]34
$innerCmd = "powershell.exe -NoProfile -ExecutionPolicy Bypass -File $q$supervisorScript$q -Repo $q$Repo$q -EgptHome $q$EgptHome$q"
# 0 = hidden window, False = don't wait -- the supervisor loops forever, Explorer's own
# Startup-folder processing must not block on it.
$vbsContent = @"
' egpt-daemon-supervisor.vbs -- auto-generated by setup/register-startup.ps1. Do not edit
' by hand; re-run that script after moving/editing the repo instead.
Set objShell = CreateObject("WScript.Shell")
objShell.Run "$($innerCmd -replace '"', '""')", 0, False
"@

Set-Content -Path $launcherPath -Value $vbsContent -Encoding ASCII

Write-Host "Installed Startup-folder launcher:" -ForegroundColor Green
Write-Host "  $launcherPath"
Write-Host "  runs : $innerCmd"
Write-Host ""
Write-Host "Takes effect on the NEXT logon (or run it once now to start immediately):"
Write-Host "  wscript.exe `"$launcherPath`""
